# 休息中の凝集性に影響する要因  
以下の分析では、オスからの攻撃のリスクが群れの凝集性に影響するかを検討する。  

## データの加工  
まず、休息集団内のメス数と、3m以内のメス数、5m以内のメス数(2019は除く)を算出する。また、近接に*TY*または*IT*がいたかを示した列を作成する。    
```{r}
adult19 <- unique(female19 %>% filter(age >= 6) %>% .$femaleID)
adult20 <- unique(female20 %>% filter(age >= 6) %>% .$femaleID)
adult21 <- unique(female21 %>% filter(age >= 6) %>% .$femaleID)

focal_raw_fin %>% 
  filter(study_period != "m18") %>% 
   separate(x0_1m, into = str_c("x0_1m",1:11), sep = ",") %>% 
  separate(x1_3m, into = str_c("x1_3m",1:15), sep = ",") %>% 
  separate(x3_5m, into = str_c("x3_5m",1:16), sep = ",") %>% 
  separate(x5_10m, into = str_c("x5_10m", 1:9), sep = ",")  %>% 
  pivot_longer(cols = x0_1m1:x5_10m5,
               names_to = "proximity",
               values_to = "ID") %>% 
  mutate(proximity = ifelse(str_detect(proximity,"x0_1m"),"x0_1m",
                            ifelse(str_detect(proximity,"x1_3m"),"x1_3m",
                                   ifelse(str_detect(proximity,"x3_5m"),"x3_5m",
                                          ifelse(str_detect(proximity,"x5_10m"),"x5_10m","NA"))))) %>% 
  filter(RG == "1") %>% 
  filter(!is.na(ID)) %>% 
  filter((study_period == "m19" & ID %in% adult19)|(study_period == "m20" & ID %in% adult20)|(study_period == "m21" & ID %in% adult21)) -> focal_prox

## 休息集団
RG_female <- focal_prox %>% 
  group_by(date, no_focal, time) %>% 
  summarise(RGfemale = n()) %>% 
  ungroup()

## 3m近接  
x3m_female <- focal_prox %>% 
  filter(proximity %in% c("x0_1m","x1_3m")) %>% 
  group_by(date, no_focal, time) %>% 
  summarise(x3m_female = n()) %>% 
  ungroup()

## 5m近接  
x5m_female <- focal_prox %>% 
  filter(proximity %in% c("x0_1m","x1_3m","x3_5m")) %>% 
  group_by(date, no_focal, time) %>% 
  summarise(x5m_female = n()) %>% 
  ungroup()

## 元データに結合  
focal_raw_fin %>% 
  left_join(RG_female, by = c("date","no_focal","time")) %>% 
  left_join(x3m_female, by = c("date","no_focal","time")) %>% 
  left_join(x5m_female, by = c("date","no_focal","time")) %>% 
  replace_na(list(RGfemale = 0, x3m_female = 0, x5m_female)) %>% 
  replace_na(list(x0_1m = "NA",x1_3m = "NA", x3_5m = "NA", x5_10m = "NA")) %>% 
  mutate(TY_10m = ifelse(str_detect(x0_1m,"TY")|str_detect(x1_3m,"TY")|str_detect(x3_5m,"TY")|str_detect(x5_10m,"TY"),1,0),
         TY_5m = ifelse(str_detect(x0_1m,"TY")|str_detect(x1_3m,"TY")|str_detect(x3_5m,"TY"),1,0),
         TY_3m = ifelse(str_detect(x0_1m,"TY")|str_detect(x1_3m,"TY"),1,0)) %>% 
  mutate(IT_10m = ifelse(str_detect(x0_1m,"IT")|str_detect(x1_3m,"IT")|str_detect(x3_5m,"IT")|str_detect(x5_10m,"IT"),1,0),
         IT_5m = ifelse(str_detect(x0_1m,"IT")|str_detect(x1_3m,"IT")|str_detect(x3_5m,"IT"),1,0),
         IT_3m = ifelse(str_detect(x0_1m,"IT")|str_detect(x1_3m,"IT"),1,0))-> focal_raw_prox
```

作成したデータは以下の通り。  
```{r}
datatable(focal_raw_prox,
          options = list(scrollX = 80),
          filter = list(position = "top"))
```


```{r}
focal_raw_prox %>% 
  filter(RG == "1") %>% 
  filter(TY == "1") %>% 
  filter(study_period != "m18") %>% 
  filter(rs2 == "0") %>% 
  group_by(date,no_focal, no_ntm,no_est, rs2, study_period) %>% 
  summarise(N = sum(TY_10m),
            n = n()) %>%
  ungroup() %>% 
  filter(n >= 10) %>% 
  ggplot(aes(x = no_ntm, y = N/n))+
  geom_count()+
  facet_wrap(~study_period)+
  geom_smooth(method = "glm")

a <- focal_raw_prox %>% 
  filter(rs2 == 0) %>% 
  filter(RG == "1") %>% 
  filter(RGsuc3 == "1") %>% 
  filter(!is.na(RGfemale)) %>% 
  filter(time %% 5 == 4) %>% 
  filter(study_period != "m18") %>% 
  mutate(female_rate = RGfemale/no_female)

a %>% 
  ggplot(aes(x = no_ntm, y = RGfemale/no_female))+
  geom_count(aes(color = TY_10m))+
  facet_grid(~TY_10m)+
  geom_smooth(method = "glm")+
  theme(aspect.ratio = 0.5)

a$RGfemale

r <- brm(data = a %>% mutate(date = as.factor(date)),
           RGfemale|trials(no_female) ~ no_ntm*TY_10m +  no_est + study_period + (1|subject) + (1|no_focal) + (1|date),
           prior = c(prior(student_t(4,0,10), class = "b"),
                           prior(student_t(4,0,10), class = "Intercept"),
                           prior(student_t(3,0,4), class = "sd")),
                 control=list(adapt_delta = 0.9999, max_treedepth = 22),
           family = "binomial",
           backend = "cmdstanr")

d <- dh_check_brms(r)

testZeroInflation(d)

estimate_slopes(r,
                trend = "no_ntm",
                at = c("TY_10m = c(0,1)"))

pp_check(r)

estimate_contrasts(r,
                contrast = "TY_10m = c(0,1)",
                at = c("no_ntm"))

model_parameters(r)
```


```{r}
focal_prox %>%
  filter(RG == "1") %>% 
  filter(TY != "2") %>% 
  mutate(TY = as.factor(TY)) %>% 
  group_by(no_female, subject, rs2, TY, IT, no_ntm, no_est) %>% 
  summarise(N = n(),
            mean = mean(RGsize/no_female, na.rm = TRUE),
            max = max(RGsize)) %>%
  ungroup() %>% 
  filter(rs2 == "0", N >= 10) %>% 
  ggplot(aes(x = no_ntm, y = mean))+
  geom_count(aes(color = TY))+
  geom_smooth(aes(color = TY))
```


