---
title: "Cohesion"
author: "yamaguchi"
date: "`r Sys.Date()`"
output: 
  rmdformats::readthedown:
   df_print: "paged"
   toc_depth: 4  
---

本稿の目的は、

```{r, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE, fig.align = "left")
```

# パッケージの読み込み  
```{r}
library(tidyverse)
library(lubridate)
library(DT)
library(lemon)
library(patchwork)
library(extrafont)
require(systemfonts)
require(fontregisterer)
library(survival)
library(eha)
library(flexsurv)
library(coxme)
library(survminer)
library(ggsurvfit)
library(lme4)
library(brms)
library(glmmTMB)
library(DHARMa)
library(easystats)
library(rstan)
rstan_options(auto_write = TRUE) 
options(mc.cores = parallel::detectCores()) 
```

```{r}
focal_data <- read_csv("C:/Users/Tsubasa Yamaguchi/Desktop/Study/data/combined_data/focal_combined_new.csv")
```

```{r}
focal_data %>% 
  mutate(RG = ifelse(activity %in% c("R","G") & TG == "G",1,0)) %>% 
  group_by(no_focal, date, season, subject) %>% 
  summarise(N = rle(RG)$lengths,
            RG = rle(RG)$values) %>% 
  filter(RG == "1") %>% 
  mutate(N_minus = N-1) %>% 
  ungroup()-> N_suc

N_suc %>% 
  group_by(N_minus) %>% 
  summarise(num = n()) %>% 
  ggplot(aes(x = N_minus, y = num))+
  geom_col()+
  scale_x_continuous(breaks = seq(0,121,1))
```

ゼロ過剰モデル  
```{r}
r <- brm(bf(N_minus ~ season +  (1|subject),
         zi ~ 1 + (1|subject)),
         family = zero_inflated_negbinomial(),
         iter = 5000, warmup = 2500, seed = 13,
         control=list(adapt_delta = 0.999, max_treedepth = 15),
         backend = "cmdstanr",
         data = N_suc,
         file = "model/r.rds")

r2 <- brm(N_minus ~ season +  (1|subject),
         family = negbinomial,
         iter = 5000, warmup = 2500, seed = 13,
         control=list(adapt_delta = 0.999, max_treedepth = 15),
         backend = "cmdstanr",
         data = N_suc,
         file = "model/r2.rds")
```

```{r?}
set.seed(123)

coef(r) %>% 
  data.frame() %>% 
  select(1,5,9,13) %>% 
  rename(In = 1, ziIn = 2, M8 = 3, M9 = 4) %>% 
  bind_cols(data.frame(C9 = rep(0,18))) %>% 
  rownames_to_column(var = "subject") %>% 
  pivot_longer(M8:C9, values_to = "coef", names_to = "season")-> coefs

N_suc %>% 
  select(subject, season) %>% 
  left_join(coefs, by = c("subject", "season")) %>% 
  mutate(prob = inv_logit_scaled(ziIn)) %>% 
  mutate(onezero = ifelse(rbernoulli(1383,prob),0,1)) %>% 
  mutate(mu = exp(In + coef)) %>% 
  mutate(N = onezero*rnbinom(1383, mu = exp(In + coef),size = posterior_summary(r)[7,1])) %>% 
  ggplot(aes(x = N ))+
  geom_histogram(binwidth = 1,
                 fill  = "red3",
                 alpha = 0.3)+
  geom_col(data = N_suc %>% 
  group_by(N_minus) %>% 
  summarise(num = n()),
  aes(x = N_minus, y = num),
  alpha = 0.5) +
  theme_bw()+
  scale_y_continuous(expand= c(0.01,0))+
  theme(aspect.ratio = 0.8) -> p1
```

```{r}
set.seed(123)

coef(r2) %>% 
  data.frame() %>% 
  select(1,5,9) %>% 
  rename(In = 1,  M8 = 2, M9 = 3) %>% 
  bind_cols(data.frame(C9 = rep(0,18))) %>% 
  rownames_to_column(var = "subject") %>% 
  pivot_longer(M8:C9, values_to = "coef", names_to = "season")-> coefs2

N_suc %>% 
  select(subject, season) %>% 
  left_join(coefs2, by = c("subject", "season")) %>% 
  mutate(N = rnbinom(1383, mu = exp(In + coef), size = posterior_summary(r2)[5,1])) %>% 
  ggplot(aes(x = N ))+
  geom_histogram(binwidth = 1,
                 fill  = "red3",
                 alpha = 0.3)+
  geom_col(data = N_suc %>% 
  group_by(N_minus) %>% 
  summarise(num = n()),
  aes(x = N_minus, y = num),
  alpha = 0.5)+
  theme_bw()+
  scale_y_continuous(expand= c(0.01,0))+
  theme(aspect.ratio = 0.8) -> p2

p1 + p2
```






